version: '3'

services:
  shared-dotnet-extentions-v2-dc:
    env_file: ../config/.env
    build: 
      context: .
      dockerfile: Dockerfile

    volumes:
      - ../:/workspace:cached

    user: root
    
    # Overrides default command so things don't shut down after the process ends.
    command: sleep infinity


